web:
  enabled: true
  addr: ":8080"

snmp:
  version: "2c"
  community: "public"
  timeout: "2s"
  retries: 1
  max_repetitions: 25

targets:
  - name: "R1"
    address: "10.10.10.1"
    port: 161
  
  - name: "R2"
    address: "10.10.20.2"
    port: 161

collect:
  system: true
  interfaces: true
  ip_routes: true

oids:
  system:
    sysDescr:  "1.3.6.1.2.1.1.1.0"
    sysUpTime: "1.3.6.1.2.1.1.3.0"
    sysName:   "1.3.6.1.2.1.1.5.0"

  interfaces:
    ifDescr:      "1.3.6.1.2.1.2.2.1.2"
    ifOperStatus: "1.3.6.1.2.1.2.2.1.8"
    ifInOctets:   "1.3.6.1.2.1.2.2.1.10"
    ifOutOctets:  "1.3.6.1.2.1.2.2.1.16"

  ip_routes:
    ipRouteDest:    "1.3.6.1.2.1.4.21.1.1"
    ipRouteIfIndex: "1.3.6.1.2.1.4.21.1.2"
    ipRouteNextHop: "1.3.6.1.2.1.4.21.1.7"
    ipRouteType:    "1.3.6.1.2.1.4.21.1.8"
    ipRouteMask:    "1.3.6.1.2.1.4.21.1.11"

database:
  enabled: true
  host: "127.0.0.1"    
  port: 5432
  name: "tsdb"
  user: "postgres"
  password: "postgres"
  sslmode: "disable"
  batch_size: 200
  max_conns: 10
  min_conns: 2
  max_conn_lifetime: "30m"